name: Java CI
on:
    push:
        branches:
            -java
    pull_request:
        branches:
            -java
jobs:
    jar:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Using this repo's thingy
        run: |
            echo "{${ANDROID_HOME}/build-tools/30.0.1}"
            echo "{REPOSITORY_NAME}={$GITHUB_REPOSITORY}"
        - name: Enable java : JDK 14
        uses: actions/setup-java@v1
        with:
            java-version: 14
        - name: On terminal excutes gradle
        run: ./gradlew deploy
        - name: Upload built jar file
        uses: actions/upload-artifact@v2
        with:
            #uses environment variable which set from above
            name: ${{env.REPOSITORY_NAME}}
            path: build/libs/${{env.REPOSITORY_NAME}}.jar
