name: Java CI

on:
    push:
        branches:
            - java
    pull_request:
        branches:
            - java

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up repo name
      uses: allenevans/set-env@v2.0.0
      with:
        repository name: "temp"
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build mod jar
      run: |
        echo "${{ env.REPOSITORY_NAME }}=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')"
        chmod +x gradlew
        ./gradlew jar
    - name: Upload built jar file
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.REPOSITORY_NAME }}
        path: build/libs/${{ env.REPOSITORY_NAME }}-java.jar
