name: Java CI

on:
    push:
        branches:
            - java
    pull_request:
        branches:
            - java

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up PATH
      run: echo "REPOSITORY_NAME=multi-lib"
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build mod jar
      run: |
        echo "::debug::$REPOSITORY_NAME"
        chmod +x gradlew
        ./gradlew jar
    - name: Upload built jar file
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.REPOSITORY_NAME }}
        path: build/libs/${{ env.REPOSITORY_NAME }}-java.jar
